### ISSUE TITLE
Segmentation fault when trying to initialize opengl context

### ISSUE THREAD

**Issue by rien333** [OpenProgger/phonon-mpv#12]
I'm using phonon-mpv (build from master) with okular. When I open a pdf with a video, it doesn't autoplay (like in the other backends), and when I click on the video okular crashes with the following error:

```shell-session
$ okular pitch.pdf
... # bunch of gtk theming warnings
QHash<QString, QString> Phonon::PulseSupport::streamProperties(QString) const RequestedUUID Could not be found. Returning with empty properties.
QHash<QString, QString> Phonon::PulseSupport::streamProperties(QString) const RequestedUUID Could not be found. Returning with empty properties.
org.kde.okular.ui: Unable to inhibit screensaver QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.freedesktop.ScreenSaver was not provided by any .servicefiles")
QHash<QString, QString> Phonon::PulseSupport::streamProperties(QString) const RequestedUUID Could not be found. Returning with empty properties.
PHONON-MPV [FATAL__] failed to initialize mpv GL context: something happened
Segmentation fault (core dumped)
```

Note that the crash only occurs in okular's "presentation mode". Okular doesn't crash when in "normal mode", but doesn't play the video either. Instead,  when in normal mode, it doesn't autoplay and shows a blackbox where the video is when I click on it. 

Other backends work fine on the same pdf. I could send you the pdf, if you like. Note that I'm using a really recent version of mpv, maybe something within libmpv changed?

## System info

```console
$ uname -mor
5.3.13-arch1-1 x86_64 GNU/Linux 

$ mpv --version
mpv 0.30.0-212-gf09570664f Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Fri Nov 29 00:43:53 CET 2019
ffmpeg library versions:
   libavutil       56.36.101
   libavcodec      58.64.101
   libavformat     58.35.100
   libswscale      5.6.100
   libavfilter     7.67.100
   libswresample   3.6.100
ffmpeg version: N-95902-g16fa513392

$ okular --version
okular 1.8.3
```

**Comment by zkvsky** [comment]
@rien333 are you using AMD GPU? If yes, try mpv git

**Comment by rien333** [comment]
I'm using an intel GPU, and I'm already on mpv-git (which was compiled today, as you can see). mpv itself works fine.

**Comment by rien333** [comment]
@barolo  So videos in okular work for you? I could send you an MWE if you can't reproduce (still running the latest and greatest mpv)

**Comment by rien333** [comment]
Oh it just sort of worked for the first time (in non-presentation mode at least)! For some reason the output size is still really off compared to phonon-vlc and phonon-gstreamer. Going into presentation mode stills crashes okular with the error from my original post. Furthermore, the video doesn't loop.

**Comment by sl1pkn07** [comment]
same here only play probe in phononsettings

~~~
(gdb) bt full
#0  0x0000555555ea1540 in  ()
#1  0x00007ffff6ca8d0a in QMetaObject::invokeMethod(QObject*, char const*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
    (obj=0x555555df03c0, member=0x7fffd67a147e "mpv_event_loop", type=Qt::QueuedConnection, ret=..., val0=..., val1=..., val2=..., val3=..., val4=..., val5=..., val6=..., val7=..., val8=..., val9=...) at kernel/qmetaobject.cpp:1508
        sig = {a = 512, s = 17, ptr = 0x7fffdcbfd950 "mpv_event_loop()", {array = "mpv_event_loop()\000\000\000\000\000\000\000\000\000KQ\205H\331\373\002\330n\226UUU\000\000\000\000\000\000\000\000\000\000pݿ\334\377\177\000\000\000\000\000\000\000\000\000\000\257\204\016\301\377\177\000\000\360\264\212UUU\000\000\360\264\212UUU\000\000\005\240\361\277\377\177\000\000\000\000\000\000\000\000\000\000pݿ\334\377\177", '\000' <repeats 18 times>, "\001\000\000\000\000\000\000\000\241E\362\277\377\177\000\000\000\000\000\000\000\000\000\000\220\255\001\250\377\177\000\000\364\305ދ/\216F@ ܿ\334\000\000\000\000\001\000\000\000\000\000\000\000\360\264\212UUU\000\000a\340\271\367p\341?@\000\023\004\250"..., q_for_alignment_1 = 7954894494585221229, q_for_alignment_2 = 6.206500385793781e+223}}
        len = <optimized out>
        typeNames = {0x7fffdcbfd8f0 "", 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
        paramCount = <optimized out>
        meta = <optimized out>
        idx = <optimized out>
        method = {mobj = 0x6, handle = 3219803514}
#2  0x00007fffd678e3d7 in  () at /usr/lib/qt/plugins/phonon4qt5_backend/phonon_mpv.so
#3  0x00007fffbfefd401 in  () at /usr/lib/libmpv.so.2
#4  0x00007fffbfeff155 in  () at /usr/lib/libmpv.so.2
#5  0x00007fffbfeff4b3 in  () at /usr/lib/libmpv.so.2
#6  0x00007fffc006b5aa in  () at /usr/lib/libmpv.so.2
#7  0x00007fffbfef7e77 in  () at /usr/lib/libmpv.so.2
#8  0x00007fffbfefd802 in  () at /usr/lib/libmpv.so.2
#9  0x00007ffff628c9eb in start_thread (arg=<optimized out>) at pthread_create.c:444
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737323255568, -2112806224817371533, -232, 2, 140737488341696, 140736888561664, 2112879343352333939, 2112788280706778739}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#10 0x00007ffff6310dfc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
~~~

greetings

**Comment by OpenProgger** [comment]
The current release includes a fix that make phononsettings work again so I will close this. If the segmentation faults persist it can be reopened again.
